export default {
    nameBots: [
        { name: 'Naruto', id: 1 },
        { name: 'Sasuke', id: 2 },
        { name: 'Sakura', id: 3 },
        { name: 'Kakashi', id: 4 },
        { name: 'Hinata', id: 5 },
        { name: 'Shikamaru', id: 6 },
        { name: 'Choji', id: 7 },
        { name: 'Neji', id: 8 },
        { name: 'Shino', id: 9 },
        { name: 'Ino', id: 10 },
        { name: 'Chocho', id: 11 },
        { name: 'Goyu', id: 12 },
        { name: 'Haku', id: 13 },
        { name: 'Itachi', id: 14 },
        { name: 'Zabuza', id: 15 },
        { name: 'Itadori', id: 16 },
        { name: 'Megumi', id: 17 },
        { name: 'Yuji', id: 18 },
        { name: 'Maki', id: 19 },
        { name: 'Toge', id: 20 },
        { name: 'Obito', id: 21 },
        { name: 'Madara', id: 22 },
        { name: 'Orochimaru', id: 23 },
        { name: 'Pain', id: 24 }
    ],
};
